// Rust doesn't have exceptions
// it has Result type and panic!


fn main() {
    // panic!("crash and burn!");

    let v = vec![1, 2, 3];

    // v[100]; This would cause a panic (but not a buffer overead)
}
